# .github/workflows/publish-to-pypi.yml

name: Publish Python Package to PyPI

on:
  # Запускается при создании новых релизов в GitHub
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Получает исходный код из репозитория
      - name: Check out the repository
        uses: actions/checkout@v4

      # Шаг 2: Устанавливает Python нужной версии
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Шаг 3: Устанавливает Poetry
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      # Шаг 3.5: очищаем старые артефакты, чтобы не залить предыдущую версию
      - name: Clean dist artifacts
        run: rm -rf dist

      # Шаг 4: Собирает пакет, создаём wheel и sdist в каталоге /dist
      - name: Build package
        run: poetry build

      # Шаг 5: Публикует пакет в TestPyPI
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

      # Шаг 6: Публикует пакет в основной PyPI. Тег релиза должен начинаться с 'v' (типа, v0.5.0)
      - name: Publish package to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
